### ISSUE TITLE
Installation requires --prefer-source composer flag

### ISSUE THREAD

**Issue by jausions** [lmc-eu/steward#118]
Apparently, composer doesn't want to install the dependencies without the --prefer-source option. At least that's my experience. There are at least two dependencies that caused me problems: phpunit/phpunit-mock-objects and florianwolters/component-util-singleton. Some missing files in the manifest of those packages.

Tested for dependencies of version 2.1 of lmc/steward.

If you confirm the problem, you may want to add something in the Readme / Installation section.

**Comment by OndraM** [comment]
@jausions Hi, thanks for the report. Could you please post full log from composer installation with the errors? And also the command you used to start Steward installation, please? It would really help us to trace the problem.

Thank you!

**Comment by jausions** [comment]
```
E:\Selenium-tests\BALIDF-CRM>composer require --dev lmc/steward
Using version ^2.1 for lmc/steward
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 48 installs, 0 updates, 0 removals
  - Installing symfony/process (v3.2.6) Loading from cache
  - Installing symfony/finder (v3.2.6) Loading from cache
  - Installing symfony/filesystem (v3.2.6) Loading from cache
  - Installing symfony/event-dispatcher (v3.2.6) Loading from cache
  - Installing psr/log (1.0.2) Loading from cache
  - Installing symfony/debug (v3.2.6) Loading from cache
  - Installing symfony/polyfill-mbstring (v1.3.0) Loading from cache
  - Installing symfony/console (v3.2.6) Loading from cache
  - Installing symfony/yaml (v2.8.18) Loading from cache
  - Installing sebastian/version (2.0.1) Loading from cache
  - Installing sebastian/resource-operations (1.0.0) Loading from cache
  - Installing sebastian/recursion-context (2.0.0) Loading from cache
  - Installing sebastian/object-enumerator (2.0.1) Loading from cache
  - Installing sebastian/global-state (1.1.1) Loading from cache
  - Installing sebastian/exporter (2.0.0) Loading from cache
  - Installing sebastian/environment (2.0.0) Loading from cache
  - Installing sebastian/diff (1.4.1) Loading from cache
  - Installing sebastian/comparator (1.2.4) Loading from cache
  - Installing doctrine/instantiator (1.0.5) Loading from cache
  - Installing phpunit/php-text-template (1.2.1) Loading from cache
  - Installing phpunit/phpunit-mock-objects (3.4.3) Downloading: 100%
Installation failed, deleting ./composer.json.


  [ErrorException]
  ZipArchive::extractTo(E:\Selenium-tests\BALIDF-CRM/vendor/composer/be8d04f9/sebastianbergmann-phpunit-mock-objects-3ab72b6\tests\MockObject\Generator/class_implementing_interface_dont_call_parent_constructor.phpt): failed to open stream: No such file or directory


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```

When attempting to install this dependency separately, it fails too:

```
E:\Selenium-tests\BALIDF-CRM>composer require --dev florianwolters/component-util-singleton:0.3.2
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing florianwolters/component-core-stringutils (v0.3.1) Downloading: 100%
Installation failed, deleting ./composer.json.


  [ErrorException]
  ZipArchive::extractTo(E:\Selenium-tests\BALIDF-CRM/vendor/composer/0b0b4282/FlorianWolters-PHP-Component-Core-StringUtils-51978fa\src\tests\unit-tests\php\FlorianWolters\Component\Core/RandomStringUtilsTest.php): failed to open stream: No such file or directory


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```

**Comment by OndraM** [comment]
From a quick search this looks like an Windows issue - and some kind of path limit there. See https://github.com/composer/composer/issues/3755 

Suggested solution is to try to move the repository to some "shorter" directory, like `E:\test`, could you try this?

**Comment by jausions** [comment]
Yes, I did find that information as well. Some path length limited to 260 characters on Windows. I already took care of that (`mklink /J link target`) to shorten the path... just in case :-)

However, all the paths involved are now shorter than 260... **and the problem goes away when using `--prefer-source` *composer* flag**.

**Comment by jausions** [comment]
Maybe it has to do with how *ZipArchive* extracts the files. In any case, it would be too bad to give up on using your package if one fails to install it easily. A small note in the installation section would go a long way to ease the process :-)

**Comment by OndraM** [comment]
@jausions I see, however this it the first report about similar issue on Windows (and there are many Steward users using Windows, so I guess this is rare problem). Even the Composer issue https://github.com/composer/composer/issues/3755 mentions this bug appears inconsistently... But may there be more reports in future, we may add the note.

Thank you and enjoy using Steward :).
