### ISSUE TITLE
Can't figure out instructions

### ISSUE THREAD

**Issue by sherylroberts** [lmc-eu/steward#121]
I've tried the getting started instructions and i'm hitting a wall. I'm able to run a test. I actually had to install geckodriver to make it load firefox and then I end up getting this error message

`1) My\TitlePageTest::testShouldContainSearchInput
My\TitlePageTest> Error: Class 'WebDriverBy' not found`

Here is my composer.json
```
{
    "require": {
        "lmc/steward": "^2.1"
    },
    "autoload-dev": {
        "psr-4": {
            "My\\": "tests/",
            "" : "tests/"
        }
    }
}
```

What am I doing wrong?

**Comment by OndraM** [comment]
Hi @sherylroberts,
you don't need to specify namespaces autoloading in `autoload-dev` section, rather use the `autoload` section. So the most simple compose.json could look like this:

```json
{
    "require": {
        "lmc/steward": "^2.1"
    },
    "autoload": {
        "psr-4": {
            "My\\": "tests/"
        }
    }
}
```

If you have this file in eg. selenium-tests/compose.json directory, go to this directory and run composer install:
``sh
$ cd selenium-tests
$ composer install
``

It you now place your tests in `selenium-tests/tests/` directory and run them, it should work, and the autoloading will be handled via Composer.

```php
<?php

namespace My;

use Facebook\WebDriver\WebDriverBy;
use Lmc\Steward\Test\AbstractTestCase;

class GithubSearchTest extends AbstractTestCase
{
    public function testShouldSubmitSearchFromHeaderAndShowResults()
    {
        $this->wd->get('https://github.com/');

        $searchInput = $this->wd->findElement(WebDriverBy::cssSelector('.header-search-input'))

        ...
    }
}

```

If you will still face the problem, please post the whole test file you are trying to run.

**Comment by OndraM** [comment]
Hi @sherylroberts,
you don't need to specify namespaces autoloading in `autoload-dev` section, rather use the `autoload` section. So the most simple compose.json could look like this:

```json
{
    "require": {
        "lmc/steward": "^2.1"
    },
    "autoload": {
        "psr-4": {
            "My\\": "tests/"
        }
    }
}
```

If you have this file in eg. selenium-tests/compose.json directory, go to this directory and run composer install:
``sh
$ cd selenium-tests
$ composer install
``

It you now place your tests in `selenium-tests/tests/` directory and run them, it should work, and the autoloading will be handled via Composer.

```php
<?php

namespace My;

use Facebook\WebDriver\WebDriverBy;
use Lmc\Steward\Test\AbstractTestCase;

class GithubSearchTest extends AbstractTestCase
{
    public function testShouldSubmitSearchFromHeaderAndShowResults()
    {
        $this->wd->get('https://github.com/');

        $searchInput = $this->wd->findElement(WebDriverBy::cssSelector('.header-search-input'))

        ...
    }
}

```

If you will still face the problem, please post the whole test file you are trying to run.

**Comment by katapofatico** [comment]
Hello,

I have exactly the same issue:
**a)** To update documentation: We have to run Selenium with gecko driver, and works correctly:
`java -Dwebdriver.gecko.driver=path_to_geckodriver_file -jar ./vendor/bin/seleni-server-standalone-3.3.1.jar`

**b)** I follow exactly both the main instructions and your comment instructions. The framework (phpunit, webdriver and firefox) run correctly, but the tests fails with:
`Error: Class 'WebDriverBy' not found`

### 1 Files
composer.json:
```json
{
    "require": {
        "lmc/steward": "^2.1"
    },
    "autoload": {
        "psr-4": {
            "My\\": "tests/"
        }
    }
}
```
TitlePageTest.php:
```php
<?php
// selenium-tests/tests/TitlePageTest.php

namespace My; // Note the "My" namespace maps to the "tests" folder, as defined in the autoload part of `composer.json`.


use Facebook\WebDriver\WebDriverBy;
use Lmc\Steward\Test\AbstractTestCase;

class TitlePageTest extends AbstractTestCase
{
    public function testShouldContainSearchInput()
    {
        // Load the URL (will wait until page is loaded)
        $this->wd->get('http://www.w3.org/'); // $this->wd holds instance of \RemoteWebDriver

        // Do some assertion
        $this->assertContains('W3C', $this->wd->getTitle());

        // You can use $this->log(), $this->warn() or $this->debug() with sprintf-like syntax
        $this->log('Current page "%s" has title "%s"', $this->wd->getCurrentURL(), $this->wd->getTitle());

        // Make sure search input is present
        $searchInput = $this->wd->findElement(\WebDriverBy::cssSelector('#search-form input'));
        // Or you can use syntax sugar provided by Steward (this is equivalent of previous line)
        $searchInput = $this->findByCss('#search-form input');

        // Assert title of the search input
        $this->assertEquals('Search', $searchInput->getAttribute('title'));
    }
}
```
### 2 Variables
**a)** Following main instructions, I execute `composer dump-autoload` after installing steward, including the autoload section on composer.json and creating tests/TitlePageTest.php. Following your comment instructions, I skip it. Nothing changes.
**b)** Your comment instructions add  the line `use Facebook\WebDriver\WebDriverBy;` I add this line to TitlePageTest.php and nothing changes.
**c)** I install steward skipping composer cache and dev packages: `COMPOSER_CACHE_DIR=/dev/null composer --no-dev install`. Nothing changes
**d)** I install steward folowing main instructions:
`./vendor/bin/steward install`
or your comment instructions:
`composer install`
... and nothing chages.

### 3 Enviroment
I'm running on:
- ubuntu 16.04 LTS
- PHP 7.0.15-0ubuntu0.16.04.4
- Composer 1.4.1
- Today's master version of steward

:pray: Thanks a lot!

**Comment by OndraM** [comment]
@katapofatico Hi, thanks for the report. I just tried exactly the same setup you wrote, and i works as expected on my machine, so this is weird :-(. Could you please provide some more information, so I can try to find where is the problem?

- output of `composer show` command (run from the base directory where you have you project with tests)
- the exact command you use to run steward tests
- full output of the `steward run ...` command with `-vvv` parameters

Thanks a lot!

**Comment by katapofatico** [comment]
FIXED! :dancer: 

Debugging findFileWithExtension() function on composer/ClassLoader.php I have found that removing this slash prefixing "WebDriverBy"...
before:
` $searchInput = $this->wd->findElement(\WebDriverBy::cssSelector('#search-form input'));`
after:
`$searchInput = $this->wd->findElement(WebDriverBy::cssSelector('#search-form input'));`
... solves the problem:
`[OK] Testcases executed: 1 (passed: 1)`

 :beer:

(Now you can update the documentation: this fix and the gecko driver one) Thanks!

**Comment by katapofatico** [comment]
Maybe you can include the gecko driver (and others needed, if there are) on installation: vendor/mozilla/geckodriver

**Comment by OndraM** [comment]
@katapofatico 🥇  Oh, I see, nice catch! Aren't you interested in sending pull request to remove the unnecessary backshlas?

**Comment by katapofatico** [comment]
@OndraM 
Ready: https://github.com/lmc-eu/steward/pull/125

**Comment by OndraM** [comment]
@katapofatico I also prepared new Wiki page, explaining how to use the Geckodriver. What do you think?

**Comment by katapofatico** [comment]
@OndraM It's easy:
1. You can read the explanation from here: http://www.softwaretestingstudio.com/webdriver-gecko-exception-selenium/
2. You can download it from here: https://github.com/mozilla/geckodriver/releases
3. You can use on selenium launching like this:
`java -Dwebdriver.gecko.driver=[path_to_geckodriver] -jar ./vendor/bin/selenium-server-standalone-3.3.1.jar`

Moreover and better, you can also add instructions to use other webdrivers. For example:
1. You can download it from here: http://phantomjs.org/
2. You can use on selenium launching it like this:
`java -Dphantomjs.binary.path=[path_to_phantomjs] -jar ./vendor/bin/selenium-server-standalone-3.3.1.jar`

Also you can launch selenium with both drivers:
`java -Dwebdriver.gecko.driver=[path_to_geckodriver] -Dphantomjs.binary.path=[path_to_phantomjs] -jar ./vendor/bin/selenium-server-standalone-3.3.1.jar`

I think the best option is to include these drivers on steward installation process: on vendor/bin/, for example.

HTH ;)

**Comment by OndraM** [comment]
@katapofatico See https://github.com/lmc-eu/steward/wiki/Selenium-server-&-browser-drivers , hope it helps for future newcomers :).

> I think the best option is to include these drivers on steward installation process: on vendor/bin/, for example.

I don't think so - these drivers are usually big binary files, and their release cycle don't match Steward releases. But I will consider suggesting some other dependencies, which can install these drivers, like https://packagist.org/packages/enm1989/chromedriver and https://packagist.org/packages/enm1989/geckodriver.

**Comment by katapofatico** [comment]
Very clear, explanatory :+1: 
Thanks from community ;)
