### ISSUE TITLE
Invalid @dataProvider causes misleading exception

### ISSUE THREAD

**Issue by katapofatico** [lmc-eu/steward#127]
Hello :)

My "HomeTest" class works great, like this:
```php
use Lmc\Steward\Test\AbstractTestCase;

class HomeTest extends AbstractTestCase {

    public function testMozilla() {
        $url = 'https://www.mozilla.org';
        $this->wd->get($url);
        $this->assertEquals('https://www.mozilla.org/en-US/', $this->wd->getCurrentURL());
    }
}
```
I want to add a data provider:
```php
use Lmc\Steward\Test\AbstractTestCase;

class HomeTest extends AbstractTestCase {

    /**
    * @dataProvider urlsProvider
    */
    public function testMozilla($url) {
        $this->wd->get($url);
        $this->assertEquals('https://www.mozilla.org/en-US/', $this->wd->getCurrentURL());
    }

    public function urlsProvider() {
        return array(
            'https://www.mozilla.org',
            'https://www.mozilla.es'
        );
    }

}
```
...and executing it with...

`./vendor/bin/steward run local phantomjs -vvv`

... the console dump this error:

`PHP Fatal error:  Uncaught InvalidArgumentException: Test case must be descendant of Lmc\Steward\Test\AbstractTestCase in [path_ommited.../]vendor/lmc/steward/src/Listener/WebDriverListener.php:40`

Please: where is the problem? The error message is difficult to interpretate, because HomeText extends AbstractTestCase. I have not any other class called AbstractTestCase in my project.

Thanks a lot!

**Comment by OndraM** [comment]
Hi @katapofatico, thanks for trying Steward!

Two issues here - first, the data provider is supposed to be an array of arrays:
```
    public function urlsProvider() {
        return array(
            array('https://www.mozilla.org'),
            array('https://www.mozilla.es'),
        );
    }
```
It should work then.

Second issue is that as you wrote - the error message is really misleading, so let me keep this issue open so that I don't forget to fix it soon. (The proper exception should be "The data provider specified for My\ProviderTest::testMozilla is invalid.")

Thanks again for the report!

**Comment by katapofatico** [comment]
Great! the array of arrays fixed my problem. Thanks again!

**Comment by katapofatico** [comment]
Sorry if I ask beginner questions, but I doubt about if this problem is due to my ignorance or is a issue on steward.

Continuing with my previous example, I have added to it a dataProvider that returns an Iterator, not an array o arrays. I have copied the example 2.7 (and 2.8, with the class CsvFileIterator) from [phpunit documentation](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers.examples.DataTest2.php):
```php
public function urlsProvider() {
        return new CsvFileIterator('data/redireccion-versiones-dominio.csv');
    }
```
> A data provider method must be public and either return an array of arrays or an object that implements the Iterator interface and yields an array for each iteration step.

... and again:
`PHP Fatal error:  Uncaught InvalidArgumentException: Test case must be descendant of Lmc\Steward\Test\AbstractTestCase in /opt/lampp/htdocs/fenix/amantis/doc/dev/vendor/lmc/steward/src/Listener/WebDriverListener.php:40`

Is steward supossed to work with Iterators as dataProviders? Where is my mistake?

Thanks!

**Comment by OndraM** [comment]
@katapofatico No problem, I'm glad to help :).

Well there is still the confusing error, sorry about that. However I just tried it and it works for me. I guess you may still be returning invalid data from the provider (or the iterator). What are the contents of the csv file? How does look the test method which accepts the data from the provider?

**Comment by katapofatico** [comment]
Thanks a lot: If it works for you then it's my problem: don't worry about it. Your questions guide to me ;)

**Comment by OndraM** [comment]
The error message is fixed in master and will be released in next version. Thanks!
