### ISSUE TITLE
Recommended way to deal with cookies

### ISSUE THREAD

**Issue by vaceletm** [lmc-eu/steward#137]
Hi,

I don't know if it's the right place to ask questions. If not feel free to guide me toward the user group/discussion/forum/slack/irc/... :)

My question is about authentication and cookies. The tests I need to automate requires to be authenticated. This works great but I'm not sure what is the recommended way to deal with cookies across tests and across test files.

How are you managing them ?

**Comment by vaceletm** [comment]
I self close: I used test dependencies and Legacy to share cookies across tests.

**Comment by OndraM** [comment]
@vaceletm Nice, this sound like an reasonable solution. You may share some of the code here if you like, for future newcomers. 

Thank you and enjoy using Steward :)
