### ISSUE TITLE
Possibility to run test one by one (not in a parallel)

### ISSUE THREAD

**Issue by dahinton11** [lmc-eu/steward#153]
Currently the default processing of test executes all test in parallel. This is great, although we have built up a large test structure with multiple files with many tests. With the default setup instructions we would have many browsers open as we tend to use the @group.
Is it possible to run a tests one after another or end to end?  Many tests are located in different files.  Is there a variable or capability option you can pass to have max amount of sessions at once?

I don't see any mention of Selenium Grid or a maxSession option. 
Would the DelayStrategy be used?

**Comment by OndraM** [comment]
Hi @NorCalCoder11 , thanks for the question!

The way it currently works is by starting all tests at once (except those delayed), and the queuing is then done by the Selenium server itself (on first come - first serve basis). Thus Steward does not currently control the number of concurrent tests - this is completely up to Selenium server.

While there may be an option to implement this inside Steward and it sounds like and interesting feature (it would require to dequeue tests each time the previous test is finished - this means adjusting the execution loop inside RunCommand), for now the most simple option is using the maxSession option and force Selenium to always open max. 1 window.

To use it, you must run selenium in the server-node mode:
`java -jar vendor/bin/selenium-server-standalone-3.5.2.jar -role hub`
`java -jar vendor/bin/selenium-server-standalone-3.5.2.jar -role node -maxSession 1`

But let me keep this issue open, this may be interesting feature for Steward 3.0 or so. Thanks for the suggestion 👍 .

**Comment by antoiba86** [comment]
I was wondering exactly this. Because my computer is not so good so it's very slow when using Steward. I am happy hearing that there is a way to use it one by one.

**Comment by OndraM** [comment]
@antoiba86 Hope the `maxSession` param would for for you fine. And thanks for your interest - I'm now thinking about prioritizing work on the "one by one" mode in Steward.

Happy testing!

**Comment by dahinton11** [comment]
@OndraM Thanks for the suggestion on the running the selenium-server node command. Although it still seems to open all the browser windows at one time. Then when that is complete it will run the tests again one at a time. Assuming Steward is still opening the browsers initially.

**Comment by OndraM** [comment]
@NorCalCoder11 And do you run both of the commands? If you start it up and go to http://localhost:4444/grid/console , switch to "Configuration" panel, there should be "maxSession: 1" - is it? Just tried this and it works for me without a problem.

![screenshot_20170901_124653](https://user-images.githubusercontent.com/793041/29966763-a31e097c-8f13-11e7-8ce6-0329065d6c3a.png)

As I wrote, Steward on the beginning opens connection to Selenium server for each of the test. And how many browsers and when are started is then up to the Selenium. With the `maxSession: 1` it will open only one window at a time.

**Comment by dahinton11** [comment]
@OndraM I had a port issue causing the Grid not to work as expected. Once I was able to address this the test ran in sync. Works great now. Thank you for the help.

**Comment by OndraM** [comment]
This could be now done using `steward run ... --parallel-limit=1`.
