### ISSUE TITLE
run a single test

### ISSUE THREAD

**Issue by q-jack** [lmc-eu/steward#167]
Is it possible to run a single test? Is there a command for this?
I have a Class which consists of multiple tests. Now I want to run just a single test.
The group property works only for whole classes.

**Comment by OndraM** [comment]
Hi @q-jack , yes, there is, I've just created Wiki page explaining the options:
https://github.com/lmc-eu/steward/wiki/Run-only-specified-tests

Let me know if there will be something unclear, I'll try to help. Thanks :)

**Comment by q-jack** [comment]
This is really awesome. Thank you very much
