### ISSUE TITLE
setting trace log geckodriver via capabilities

### ISSUE THREAD

**Issue by q-jack** [lmc-eu/steward#173]
I want to file a bug in geckodriver and therfore I need a tracelog. I have read that this could be done via capabilities. I am using the standalone server(CLI) and tried this:
`$ ./vendor/bin/steward run staging firefox --capability="log:info"`

But this won't work.
Can anybody help me on this issue?

**Comment by OndraM** [comment]
It is not possible to pass compound capabilities using the CLI option. You have to use custom capabilities resolver - https://github.com/lmc-eu/steward/issues/174#issuecomment-349359768
