### ISSUE TITLE
Custom browser size resets to abstracttestCase size

### ISSUE THREAD

**Issue by q-jack** [lmc-eu/steward#177]
I am setting a custom Capability like this:

```
`    public function resolveDesiredCapabilities(AbstractTestCase $test, DesiredCapabilities $capabilities)
    {
        $options = new ChromeOptions();
        $options->addArguments(['--window-size=1920,1080']);
        $capabilities = DesiredCapabilities::chrome();
        $capabilities->setCapability(ChromeOptions::CAPABILITY, $options);  
        return $capabilities;
    }`
```

When I start a test, the size is correct to my specified browser size. But after a couple of milliseconds it switched back to the windows size which is specified in the AbstractTestCase.

How can I keep the size of the capability.

**Comment by OndraM** [comment]
Hi, for now I would set custom browser size in custom `@before` method:

```php
    /**
     * @before
     */
    public function initBrowserSize()
    {
        $this->wd->manage()->window()->setSize(new WebDriverDimension(1920, 1080));
    }
```

Though this means to set it twice during startup (ie. reset the default behavior). Other way to "disable" the default screen size is not supported right now. But we may eg. add behavior to not set it, if  `$browserWidth` or `$browserHeight` are null (or zero). Would you find this useful?

**Comment by q-jack** [comment]
Where exactly should I insert your suggested code?
Setting it twice sounds like hack.
Aren't the capabilities not the right place to specify such meta data?

**Comment by OndraM** [comment]
The method could be placed inside you testcase class.

However, if you just need default browser size for your tests, simply set custom variables inside you abstract test case (or the appropriate test case class) like this: https://github.com/lmc-eu/steward-example/blob/master/tests/MobileTitlePageTest.php#L16-L19

**Comment by q-jack** [comment]
Thank you for answering so quick. This helped!
