### ISSUE TITLE
Looks like url "http://localhost:4444" is occupied by something else than Selenium server.

### ISSUE THREAD

**Issue by ghost** [lmc-eu/steward#188]
Hi guys

I have setup selenium server with docker and follow you're **Start Selenium server + browser inside Docker** description, everything is ok on my local ubuntu, but when I set up in my server selenium is startup very well but when run tests i got this error:
" Looks like url "http://localhost:4444" is occupied by something else  than Selenium server. Make sure Selenium server is really accessible on  this url or change it using --server-url option"  

Also, i try another answer in another issue, but they don't work

**Comment by OndraM** [comment]
Hi @Ermiaqasemi,
to be able to help you, please provide some additional information:
1) Steward version (`vendor/bin/steward --version`)
2) The whole exact command you used to start Steward and to start Docker containers
3) If you open URL http://localhost:4444/ in your browser, what do you see?

Thank you :)

**Comment by ghost** [comment]
Tanx for reply 

1. I used Steward 2.3.2.
2. first i start with 
docker run -p 4444:4444 -p 5900:5900  selenium/standalone-firefox-debug:2.53.1
then 
vendor/bin/steward run staging firefox
3. it s on attachment 
![unknown](https://user-images.githubusercontent.com/20831207/35218241-221c9204-ff83-11e7-8355-992e82519246.png).

i do it all of this in my own Ubuntu and it works well but after move on server i got that error

Thank you :)

**Comment by OndraM** [comment]
Hi, what do you mean by "move on server"?

Basically the server which Steward uses (which is http://localhost:4444/ by default or can be changed with --server-url option) must be accessible from the machine where do you run Steward.

**Comment by ghost** [comment]
I mean i configure it in our CI server , also i use --server-url but i got this when i run this command vendor/bin/steward run staging firefox
" Looks like url "http://localhost:4444" is occupied by something else than Selenium server. Make sure Selenium server is really accessible on this url or change it using --server-url option"

**Comment by OndraM** [comment]
So... And is Selenium server accessible on http://localhost:4444 (from the CI server point of view)? Could you make sure it is - like fetching the url via wget or something like that? The error message is probably accurate - there is something else occupying the port.

Could you also provide *whole* output of the command from you CI server? (When run with `-vvv` option).

**Comment by ghost** [comment]
You can find the result of elinks within the CI server ( tested http://localhost:4444 ) : 
![screenshot from 2018-01-22 15-05-16](https://user-images.githubusercontent.com/20831207/35219026-131e1842-ff86-11e7-9956-14c4dc095f41.png)


And here is the output of the mentioned command :

![screenshot from 2018-01-22 15-07-52](https://user-images.githubusercontent.com/20831207/35219082-46da7a2c-ff86-11e7-9a3e-fca1be62e6b6.png)

**Comment by OndraM** [comment]
Well, this is weird. One more thing - could you (from the same shell where you attempted to start Steward) also run command `curl http://localhost:4444/wd/hub/status`  and provide the output?

**Comment by ghost** [comment]
yeah sure : 
![screenshot from 2018-01-22 15-22-28](https://user-images.githubusercontent.com/20831207/35219487-1cf243b4-ff88-11e7-85bf-4c174cac668c.png)

**Comment by OndraM** [comment]
Ok, thank you. If I may ask for further cooperation - please try to run (again from the same shell)
`php -r "var_dump(file_get_contents('http://localhost:4444/wd/hub/status', false));"`

Also - what is you PHP version?

**Comment by ghost** [comment]
Here you are : 
![screenshot from 2018-01-22 15-36-43](https://user-images.githubusercontent.com/20831207/35220044-1ae9103c-ff8a-11e7-8955-7bf40083140d.png)

**Comment by OndraM** [comment]
I'm unable to reproduce the issue - even using same Selenium and Steward version :-/.

So we can try to isolate the issue.

Please could you create (again on the same machine) file `selenium.php` with this contents: https://gist.github.com/OndraM/18e5578fa24f133e3aa3a1165cc6db5b (or you can download the whole file using the "Raw" button) and than execute the file with `php selenium.php` (and also provide output)?

**Comment by ghost** [comment]
hey man tanx for helping , i look in my php.ini file and some file system functionality are set to false after that i change them to true , steward working wells,

tanx again :)

**Comment by OndraM** [comment]
Ok then :). Do you know which setting was the problem? Was it `allow_url_fopen`?

**Comment by ghost** [comment]
yeah as you mentioned allow_url_fopen = 0 :\

**Comment by jesusphp** [comment]
I met this trouble also ,but my setting that is allow_url_fopen = On , how to solve it? please
