### ISSUE TITLE
browserWidth drag n drop error with different dpi

### ISSUE THREAD

**Issue by q-jack** [lmc-eu/steward#190]
In my class I have defined : 
```
`    /** @var int Width of browser window */
    public static $browserWidth = 1920;
    /** @var int Height of browser window */
    public static $browserHeight = 1080;`
```

my test has a drag n drop action
`        
```
$aoiLayer = $this->wd->findElement(WebDriverBy::id('aoiLayer'));
$this->wd->action()
          ->dragAndDropBy($aoiLayer,290,100)
          ->perform();
```
`

This works well on my second screen. But when I choose a smaller device. The drag and drop is somehow out of range.
Is this an error on steward or selenium? Or it is not an error?

**Comment by OndraM** [comment]
Hi,
this maybe of issue of Selenium, php-webdriver or driver of your browser (chromedriver?). Almost for sure has Steward nothing to do with this :).
