### ISSUE TITLE
Question: How to implement the EventListener Interface

### ISSUE THREAD

**Issue by q-jack** [lmc-eu/steward#204]
Hallo there.
1. I just red that there is an EventListener interface in facebook/phpwebdriver and i would like to use the event afterNavigateTo.
I dont know where to put it and how the command will look like. the wiki does not say anything about it.
2. Question is it possible to deactivate the automatic screenshot when a test failed? 

Does someone have a link how to do that?

**Comment by OndraM** [comment]
Hi,
1. the way this works in php-webdriver is by encapsulating WebDriver instance (in Steward this is what $this->wd variable in TestCase contains). See https://github.com/cbergau/php-webdriver-examples/blob/master/tests/EventListener/EventListenerTest.php for example. I never tried it, but you can try something like 
```
        $eventFiringWebDriver = new EventFiringWebDriver($this->wd, $dispatcher);
```
(see the example for the rest) and it *may* work.

2. This is not possible right now. The `SnapshotListener` is auto-registered on startup. What is the use-case you need it for?
