### ISSUE TITLE
Error loading class "My\TitlePageTest"

### ISSUE THREAD

**Issue by hoangdangal** [lmc-eu/steward#209]
I try to run this example at my local but I got this error : 
In ProcessSetCreator.php line 305:

  Error loading class "My\TitlePageTest" from file "C:\Users\hoang\git\SeleniumWebDriver-steward\tests\TitlePageTest.
  php". Make sure the class name and namespace matches the file path.

I don't know why so can someone help me.Thanks

**Comment by vladbdev** [comment]
For anyone having this issue, make sure you run "composer dump-autoload" after you configure PSR-4 autoloading

**Comment by OndraM** [comment]
:+1: True, this is also stated in README:

> Don't forget to create the selenium-tests/tests/ directory and to run composer dump-autoload afterwards.
