### ISSUE TITLE
bin/steward.php should be just bin/steward

### ISSUE THREAD

**Issue by mhujer** [lmc-eu/steward#21]
Installing Selenium (https://github.com/lmc-eu/steward#2-install-selenium) using
`$ ./vendor/bin/steward.php install` does not work in Windows (you have to use steward.php.bat).

PHPUnit has `bin/phpunit` and `bin/phpunit.bat` which works fine.

**Comment by OndraM** [comment]
Thanks for the report. I guess it is the same with the other commands in the readme? 

And the suggestion is just to change the README, or is there any way how to make this working in windows without using the bat files?

You are also very welcome to send a PR with a fix ;-).
