### ISSUE TITLE
Define how many tests can be run in parallel

### ISSUE THREAD

**Issue by q-jack** [lmc-eu/steward#210]
Is it possible to define how many test can be executed in parallel?

**Comment by q-jack** [comment]
Any suggestions?

**Comment by OndraM** [comment]
Hi, this is currently not possible via Steward.

Current theory of operation is that Steward starts **all** tests (except those having delay and depending on other test), and they are queued on Selenium side, and executed according to capacity and free nodes of Selenium server.

However, we also find this limiting, as we are migrating to Docker-based hub with many nodes, so the Selenium capacity is close to unlimited, meaning many parallel tests produces excessive load on the application itself. So my guess is we will implement some kind of rate limiting into Steward. However no current ETA for this right now, sorry. But let me keep this issue open to track the progress.

**Comment by OndraM** [comment]
Also related to #153 .
