### ISSUE TITLE
How to run with Browserstack? Test fails, no info what actually has failed

### ISSUE THREAD

**Issue by tomekit** [lmc-eu/steward#211]
Hi,
I am trying to make it run with Browserstack using remote webdriver.

Here is my command:
`  ./vendor/bin/steward run staging firefox --server-url http://login:pass@hub.browserstack.com:80/wd/hub --tests-dir selenium-tests -vvv`

Unfortunately it's failing:
```
[2018-05-01 12:10:15] Waiting (running: 1, queued: 0, done: 0)
My\TitlePageTest> [2018-05-01 12:10:16]: Registering test results publisher "Lmc\Steward\Publisher\XmlPublisher"
My\TitlePageTest> PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
My\TitlePageTest> 
My\TitlePageTest> [2018-05-01 12:10:16]: Initializing "firefox" WebDriver for "My\TitlePageTest::testShouldContainSearchInput"
My\TitlePageTest> 
[2018-05-01 12:10:17] Finished execution of testcase "My\TitlePageTest" (result: fatal, time: 2.8 sec)
[2018-05-01 12:10:17] Waiting (running: 0, queued: 0, done: 1 [fatal: 1])
[2018-05-01 12:10:18] All testcases done in 4.0 seconds

                                                                               
 [ERROR] Testcases executed: 1 (fatal: 1) 
```

However I've no clue what actually is failing. How can I debug my problem? 
I can't see test executed on the BrowserStack, so it might be some configuration problem, where BrowserStack rejects the request.

**Comment by tomekit** [comment]
I've debugged the code and could spot that there is an exception thrown from the Webdriver:   "Session not started or terminated". I've looked deeper and spotted that I shouldn't include `wd/hub` at the end, as it's appended by the Steward already.

**Comment by OndraM** [comment]
@tomekit Hi, right, but as this was confusing behavior, this is no longer true in current master and future 3 version of Steward. But for the stable version, the wd/hub part should really not be included.
