### ISSUE TITLE
Looks like url "http://10.5.35.78:4444" is occupied by something else than Selenium server

### ISSUE THREAD

**Issue by jesusphp** [lmc-eu/steward#214]
Hi guys   
I had already setup the selenium follow the https://github.com/Modelizer/Laravel-Selenium in my virtual machine(Centos 7.0 + PHP 7.2.6 + Laravel 5.6 + Steward 3.0.0-DEV)
but i got this error when run test:

"Unexpected response from Selenium server (error reading server response)

                                                                                                                        
 [ERROR] Looks like url "http://10.5.35.78:4444" is occupied by something else than Selenium server. Make sure Selenium 
         server is really accessible on this url or change it using --server-url option  "

 My php.ini settings that is allow_url_fopen = On, How to solve it ? please

**Comment by OndraM** [comment]
Hi @jesusphp , could you please provide all commands (and their output) you use to star Steward and to start Selenium server? Also which version of Selenium server did you use?

**Comment by jesusphp** [comment]
this trouble  i was slove it, but new trouble coming。

i run this command:
#vendor/bin/steward run staging chrome

it returns :
"Steward 3.0.0-DEV is running the tests... Just for you <3!

[2018-07-19 10:24:28] Waiting (running: 3, queued: 0, done: 0)
[2018-07-19 10:24:28] Waiting (running: 0, queued: 0, done: 3 [fatal: 3])
[2018-07-19 10:24:28] All testcases done in 0.4 seconds

                                                                                                                        
 [ERROR] Testcases executed: 3 (fatal: 3) "

my testExample:
-------------------------------------SeleniumExampleTest.php-----------------------------------------------

namespace Tests;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Modelizer\Selenium\SeleniumTestCase;

class SeleniumExampleTest extends SeleniumTestCase
{
    /**
     * A basic functional test example.
     *
     * @return void
     */
    public function testBasicExample()
    {
        // This is a sample code you can change as per your current scenario
        $this->visit('/')
            ->see('Laravel')
            ->hold(3);
    }
}


i don't know how to slove it,  please help!!!     THX a lot!

**Comment by OndraM** [comment]
@jesusphp How did you start Selenium server?

Also please star steward with `-vvv` params (`vendor/bin/steward run staging chrome -vvv`) and post the output, please.

**Comment by jesusphp** [comment]
it returns when i use "vendor/bin/steward run staging chrome -vvv":

"Steward 3.0.0-DEV is running the tests... Just for you <3!
Browser: chrome
Environment: staging
Path to logs: /data/wwwroot/www/logs
Ignore delays: no
Selenium server (hub) url: http://localhost:4444/wd/hub, trying connection...OK
Searching for testcases:
 - in directory "/data/wwwroot/www/tests"
 - by pattern "*Test.php"
Found testcase file #1: /data/wwwroot/www/tests/Feature/ExampleTest.php
Found testcase file #2: /data/wwwroot/www/tests/SeleniumExampleTest.php
Found testcase file #3: /data/wwwroot/www/tests/Unit/ExampleTest.php
Testcase "Tests\Feature\ExampleTest" is prepared to be run
Testcase "Tests\SeleniumExampleTest" is prepared to be run
Testcase "Tests\Unit\ExampleTest" is prepared to be run

Starting execution of testcases
-------------------------------
[2018-07-20 10:00:45] Execution of testcase "Tests\Feature\ExampleTest" started with command:
'/usr/local/php/bin/php' '/data/wwwroot/www/vendor/lmc/steward/bin/phpunit-steward' '--log-junit=/data/wwwroot/www/logs/Tests-Feature-ExampleTest.xml' '--configuration=/data/wwwroot/www/vendor/lmc/steward/src/phpunit.xml' '--colors=always' '/data/wwwroot/www/tests/Feature/ExampleTest.php'
[2018-07-20 10:00:45] Execution of testcase "Tests\SeleniumExampleTest" started with command:
'/usr/local/php/bin/php' '/data/wwwroot/www/vendor/lmc/steward/bin/phpunit-steward' '--log-junit=/data/wwwroot/www/logs/Tests-SeleniumExampleTest.xml' '--configuration=/data/wwwroot/www/vendor/lmc/steward/src/phpunit.xml' '--colors=always' '/data/wwwroot/www/tests/SeleniumExampleTest.php'
[2018-07-20 10:00:45] Execution of testcase "Tests\Unit\ExampleTest" started with command:
'/usr/local/php/bin/php' '/data/wwwroot/www/vendor/lmc/steward/bin/phpunit-steward' '--log-junit=/data/wwwroot/www/logs/Tests-Unit-ExampleTest.xml' '--configuration=/data/wwwroot/www/vendor/lmc/steward/src/phpunit.xml' '--colors=always' '/data/wwwroot/www/tests/Unit/ExampleTest.php'
[2018-07-20 10:00:45] Waiting (running: 3, queued: 0, done: 0)
Tests\Feature\ExampleTest> [2018-07-20 10:00:45] Registering test results publisher "Lmc\Steward\Publisher\XmlPublisher"
Tests\Feature\ExampleTest> PHPUnit 7.2.6 by Sebastian Bergmann and contributors.
Tests\Feature\ExampleTest> 
Tests\Feature\ExampleTest> 
Tests\Feature\ExampleTest ERR> PHP Fatal error:  Uncaught InvalidArgumentException: Test case must be descendant of Lmc\Steward\Test\AbstractTestCase in /data/wwwroot/www/vendor/lmc/steward/src/Listener/WebDriverListener.php:60
Tests\Feature\ExampleTest ERR> Stack trace:
Tests\Feature\ExampleTest ERR> #0 /data/wwwroot/www/vendor/phpunit/phpunit/src/Framework/TestResult.php(371): Lmc\Steward\Listener\WebDriverListener->startTest(Object(Tests\Feature\ExampleTest))
Tests\Feature\ExampleTest ERR> #1 /data/wwwroot/www/vendor/phpunit/phpunit/src/Framework/TestResult.php(583): PHPUnit\Framework\TestResult->startTest(Object(Tests\Feature\ExampleTest))
Tests\Feature\ExampleTest ERR> #2 /data/wwwroot/www/vendor/phpunit/phpunit/src/Framework/TestCase.php(798): PHPUnit\Framework\TestResult->run(Object(Tests\Feature\ExampleTest))
Tests\Feature\ExampleTest ERR> #3 /data/wwwroot/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php(765): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
Tests\Feature\ExampleTest ERR> #4 /data/wwwroot/www/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(566): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
Tests\Feature\ExampleTest ERR> #5 /data/wwwroot/www/vendor/phpunit/phpunit/src/TextUI/Command.php(200):  in /data/wwwroot/www/vendor/lmc/steward/src/Listener/WebDriverListener.php on line 60
[2018-07-20 10:00:45] Finished execution of testcase "Tests\Feature\ExampleTest" (result: fatal, time: 0.3 sec)
Tests\SeleniumExampleTest> [2018-07-20 10:00:45] Registering test results publisher "Lmc\Steward\Publisher\XmlPublisher"
Tests\SeleniumExampleTest> PHPUnit 7.2.6 by Sebastian Bergmann and contributors.
Tests\SeleniumExampleTest> 
Tests\SeleniumExampleTest> [2018-07-20 10:00:45] --- Starting execution of test "testBasicExample" ---
Tests\SeleniumExampleTest> [2018-07-20 10:00:45] Initializing "chrome" WebDriver
Tests\SeleniumExampleTest> 
Tests\Unit\ExampleTest> [2018-07-20 10:00:45] Registering test results publisher "Lmc\Steward\Publisher\XmlPublisher"
Tests\Unit\ExampleTest> PHPUnit 7.2.6 by Sebastian Bergmann and contributors.
Tests\Unit\ExampleTest> 
Tests\Unit\ExampleTest> 
Tests\Unit\ExampleTest ERR> PHP Fatal error:  Uncaught InvalidArgumentException: Test case must be descendant of Lmc\Steward\Test\AbstractTestCase in /data/wwwroot/www/vendor/lmc/steward/src/Listener/WebDriverListener.php:60
Tests\Unit\ExampleTest ERR> Stack trace:
Tests\Unit\ExampleTest ERR> #0 /data/wwwroot/www/vendor/phpunit/phpunit/src/Framework/TestResult.php(371): Lmc\Steward\Listener\WebDriverListener->startTest(Object(Tests\Unit\ExampleTest))
Tests\Unit\ExampleTest ERR> #1 /data/wwwroot/www/vendor/phpunit/phpunit/src/Framework/TestResult.php(583): PHPUnit\Framework\TestResult->startTest(Object(Tests\Unit\ExampleTest))
Tests\Unit\ExampleTest ERR> #2 /data/wwwroot/www/vendor/phpunit/phpunit/src/Framework/TestCase.php(798): PHPUnit\Framework\TestResult->run(Object(Tests\Unit\ExampleTest))
Tests\Unit\ExampleTest ERR> #3 /data/wwwroot/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php(765): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
Tests\Unit\ExampleTest ERR> #4 /data/wwwroot/www/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(566): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
Tests\Unit\ExampleTest ERR> #5 /data/wwwroot/www/vendor/phpunit/phpunit/src/TextUI/Command.php(200): PHPUnit\T in /data/wwwroot/www/vendor/lmc/steward/src/Listener/WebDriverListener.php on line 60
[2018-07-20 10:00:45] Finished execution of testcase "Tests\Unit\ExampleTest" (result: fatal, time: 0.2 sec)
[2018-07-20 10:00:45] Waiting (running: 1, queued: 0, done: 2 [fatal: 2])
Tests\SeleniumExampleTest ERR> PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","name":"Tests\\SeleniumExampleTest::testBasicExample","requiredCapabilities":[]}}
Tests\SeleniumExampleTest ERR> 
Tests\SeleniumExampleTest ERR> Empty reply from server in /data/wwwroot/www/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:292
Tests\SeleniumExampleTest ERR> Stack trace:
Tests\SeleniumExampleTest ERR> #0 /data/wwwroot/www/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
Tests\SeleniumExampleTest ERR> #1 /data/wwwroot/www/vendor/lmc/steward/src/Listener/WebDriverListener.php(161): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 120000, 3600000, NULL, NULL, Object(Facebook\WebDriver\Remote\DesiredCapabilities))
Tests\SeleniumExampleTest ERR> #2 /data/wwwroot/www/vendor/lmc/steward/src/Listener/WebDriverListener.php(93): Lmc\Steward\Listener\WebDriverListener->createWebDriver(Object(Tests\Sel in /data/wwwroot/www/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php on line 292
[2018-07-20 10:00:45] Finished execution of testcase "Tests\SeleniumExampleTest" (result: fatal, time: 0.6 sec)
[2018-07-20 10:00:45] Waiting (running: 0, queued: 0, done: 3 [fatal: 3])
[2018-07-20 10:00:45] All testcases done in 0.8 seconds"

**Comment by OndraM** [comment]
It seems you run Steward on not only Selenium tests, but also some other. As you can see from the startup message:

> Found testcase file #1: /data/wwwroot/www/tests/Feature/ExampleTest.php
> Found testcase file #2: /data/wwwroot/www/tests/SeleniumExampleTest.php
> Found testcase file #3: /data/wwwroot/www/tests/Unit/ExampleTest.php

But you probably only want to run SeleniumExampleTest. So just move the other tests elsewhere, or move the SeleniumExampleTest to eg. `tests/selenium/` directory, and run steward with --tests-dir option.
