### ISSUE TITLE
undefined index:ELEMENT

### ISSUE THREAD

**Issue by ghena** [lmc-eu/steward#217]
Hello guys,

I just trying steward installation following the adviced setup.

I get this error on:

        $this->wd->get('https://www.w3.org'); // $this->wd holds instance of \RemoteWebDriver

        $this->assertContains('W3C', $this->wd->getTitle());

        **$searchInput = $this->findByCss('#search-form');**

I found advices to use  -enablePassThrough false webdriver params 

but I have an error : 
**Was passed main parameter '-enablePassThrough' but no main parameter was defined in your arg class**

I'm using windows 10
java -debug  -Dwebdriver.gecko.driver="C:\webdriver\geckodriver.exe" -jar ./vendor/bin/selenium-server-standalone-3.14.0.jar -port 4444 -role webdriver -enablePassThrough false

please let me know. regards.

**Comment by OndraM** [comment]
Hi, enablePassThrough is not supported in recent versions of Selenium server (3.9+). I suggest using Chrome until W3C protocol (and thus Firefox) landed in php-webdriver library which steward uses.
