### ISSUE TITLE
hi i run comman steward results why have one test?

### ISSUE THREAD

**Issue by champseo2017** [lmc-eu/steward#218]
I run 2 tests, but the results are just one test. Please help me.
![image](https://user-images.githubusercontent.com/32265715/45422946-f7f57b80-b6bb-11e8-8bd3-db2b44b0ab1b.png)
![image](https://user-images.githubusercontent.com/32265715/45422993-1bb8c180-b6bc-11e8-8190-70c37d19c0ad.png)

**Comment by champseo2017** [comment]
@OndraM

**Comment by OndraM** [comment]
Hi,
sorry, there is not enough information to understand the issue. Please provide:
- the command you use to run tests (with and use `-vvv` to have more verbose output).
- full output of this command

I will happily reopen the issue then :)
