### ISSUE TITLE
Working formatters?

### ISSUE THREAD

**Issue by amesas** [lmc-eu/steward#219]
Is there any working formatter from .side to PHP (php-webdriver) or NodeJS?

Or i'm missing something and .side file can be used directly from any of the current frameworks.

We need to create a few hundred tests, and it would be faster using the Selenium IDE.

**Comment by OndraM** [comment]
Hi, sorry, I don't know about any .side file converter to PHP.

Also from my experience, tests generated through Selenium IDE are usually hardly usable for some automated, repetitive and stable integration testing - most people wanting actually working testing suite ends up programming the tests manually.
