### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by takeshi3000** [lmc-eu/steward#220]
Hello,

I am looking into Steward for PHPUnit functional tests, but i'm having some problems trying to get a simple project running, I followed the instructions. But every time i run a test, i get the "results: fatal". 

The test starts and it seems to be running, but no browser is opened and it throws a fatal error. I tried multiple options for selenium(standalone and grid), passing it the only geckodriver or the chromedriver or no webdriver at all

But no matter what browser i try or how i launch selenium, i get the fatal result.

Am i doing something wrong is is my environment not set up correctly? (Trying to run on Windows 10)

Any help would be appreciated.

Selenium Command (tried with selenium 3.14, 3.4 and 3.8):

`java -Dwebdriver.gecko.driver="vendor\bin\geckodriver.exe" -jar "vendor\bin\selenium-server-standalone-3.14.0.jar"
java -Dwebdriver.chrome.driver="vendor\bin\chromedriver.exe" -jar "vendor\bin\selenium-server-standalone-3.14.0.jar"
`

Here is my command:
`vendor\bin\steward run staging firefox -vvv
`

Here is the error i get:
`C:\Frameworks\SeleniumPHP-Steward>vendor\bin\steward run staging firefox -vvv
Steward 3.0.0-DEV is running the tests... Just for you <3!
Browser: firefox
Environment: staging
Path to logs: C:\Frameworks\SeleniumPHP-Steward\logs
Ignore delays: no
Selenium server (hub) url: http://localhost:4444/wd/hub, trying connection...OK
Searching for testcases:
 - in directory "C:\Frameworks\SeleniumPHP-Steward\tests"
 - by pattern "*Test.php"
Found testcase file #1: C:\Frameworks\SeleniumPHP-Steward\tests\simpleTest.php
Testcase "My\simpleTest" is prepared to be run

Starting execution of testcases
`
[2018-09-20 10:18:22] Execution of testcase "My\simpleTest" started with command:
"C:\Program Files (x86)\PHP\v7.1\php.exe" C:\Frameworks\SeleniumPHP-Steward\vendor\lmc\steward\bin\phpunit-steward "--log-junit=C:\Frameworks\SeleniumPHP-Steward\logs/My-simpleTest.xml" --conf
iguration=C:\Frameworks\SeleniumPHP-Steward\vendor\lmc\steward\src\phpunit.xml C:\\Frameworks\SeleniumPHP-Steward\tests\simpleTest.php
[2018-09-20 10:18:22] Waiting (running: 1, queued: 0, done: 0)
My\simpleTest> [2018-09-20 10:18:23] Registering test results publisher "Lmc\Steward\Publisher\XmlPublisher"
My\simpleTest>
My\simpleTest> PHPUnit 7.3.5 by Sebastian Bergmann and contributors.
My\simpleTest>
My\simpleTest> [2018-09-20 10:18:23] --- Starting execution of test "testInitial" ---
My\simpleTest> [2018-09-20 10:18:23] Initializing "firefox" WebDriver
My\simpleTest>
[2018-09-20 10:18:24] Waiting (running: 1, queued: 0, done: 0)
[2018-09-20 10:18:35] Waiting (running: 1, queued: 0, done: 0)
[2018-09-20 10:18:47] Waiting (running: 1, queued: 0, done: 0)
[2018-09-20 10:18:58] Finished execution of testcase "My\simpleTest" (result: fatal, time: 0.7 sec)
[2018-09-20 10:18:58] Waiting (running: 0, queued: 0, done: 1 [fatal: 1])
[2018-09-20 10:18:58] All testcases done in 0.9 seconds

 [ERROR] Testcases executed: 1 (fatal: 1)
`

Readout from selenium server:
`17:18:14.277 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
17:18:23.379 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "firefox",
  "firefox_profile": "UEsDBBQAAAAAAEuKNE2BK46tKgAAACoAAAAHAAAAdXNlci5qc3VzZXJfcHJlZigiZm9jdXNtYW5hZ2VyLnRlc3Rtb2RlIiwgdHJ1ZSk7ClBLAQIUAxQAAAAAAEuKNE2BK46tKgAAACoAAAAHAAAAAAAAAAAAAAC2gQAAAAB1c2VyLmpzUEsFBgAAAAABAAEANQAAAE8AAAAAAA==",
  "name": "My\\simpleTest::testInitial",
  "pageLoadStrategy": "normal",
  "requiredCapabilities": [
  ]
}
17:18:23.381 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
`

composer.json:
`{
  "require": {
    "lmc/steward": "3.0.x-dev",
    "enm1989/chromedriver": "2.41",
    "enm1989/geckodriver": "0.20",
    "symphony/symphony": "dev-master"
  },
  "autoload": {
    "psr-4": {
      "My\\Steward\\": "src/",
      "My\\": "tests/"
    }
  }
}`

Script im trying to run: 
`<?php

namespace My;
use Facebook\WebDriver\WebDriverBy;
use Lmc\Steward\Test\AbstractTestCase;

class simpleTest extends AbstractTestCase
{

    public function testInitial()
    {
     $this ->wd->get("https://qa1.test.com");
     $this->assertContains('Request generator - Tools - Master Control Pane', $this->wd->getTitle());
     $this->log('Current page "%s" has title "%s"', $this->wd->getCurrentURL(), $this->wd->getTitle());
    }
}`

**Comment by OndraM** [comment]
Hi, Firefox is not currently supported. See https://github.com/facebook/php-webdriver/issues/469 . 

I suggest using Chrome until W3C protocol (and thus Firefox) landed in php-webdriver library which steward uses.

Also try running Steward with `-vvv` to see more verbose error output.
