### ISSUE TITLE
 Your requirements could not be resolved to an installable set of packages PHPUNIT

### ISSUE THREAD

**Issue by RichardTMiles** [lmc-eu/steward#239]
WookieeTyler:Stats.Coach richardmiles$ composer require lmc/steward
Using version ^3.0@dev for lmc/steward                      
./composer.json has been updated
Loading composer repositories with package information                                                              Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for lmc/steward ^3.0@dev -> satisfiable by lmc/steward[3.0.x-dev].
    - Conclusion: remove phar-io/manifest 1.0.1
    - Conclusion: don't install phar-io/manifest 1.0.1
    - lmc/steward 3.0.x-dev requires phpunit/phpunit ^7.4.4 -> satisfiable by phpunit/phpunit[7.4.4, 7.4.5, 7.5.0, 7.5.1, 7.5.2, 7.5.3, 7.5.4, 7.5.x-dev].
    - phpunit/phpunit 7.4.4 requires phar-io/manifest ^1.0.2 -> satisfiable by phar-io/manifest[1.0.2, 1.0.3, 1.0.x-dev].
    - phpunit/phpunit 7.4.5 requires phar-io/manifest ^1.0.2 -> satisfiable by phar-io/manifest[1.0.2, 1.0.3, 1.0.x-dev].
    - phpunit/phpunit 7.5.0 requires phar-io/manifest ^1.0.2 -> satisfiable by phar-io/manifest[1.0.2, 1.0.3, 1.0.x-dev].
    - phpunit/phpunit 7.5.1 requires phar-io/manifest ^1.0.2 -> satisfiable by phar-io/manifest[1.0.2, 1.0.3, 1.0.x-dev].
    - phpunit/phpunit 7.5.2 requires phar-io/manifest ^1.0.2 -> satisfiable by phar-io/manifest[1.0.2, 1.0.3, 1.0.x-dev].
    - phpunit/phpunit 7.5.3 requires phar-io/manifest ^1.0.2 -> satisfiable by phar-io/manifest[1.0.2, 1.0.3, 1.0.x-dev].
    - phpunit/phpunit 7.5.4 requires phar-io/manifest ^1.0.2 -> satisfiable by phar-io/manifest[1.0.2, 1.0.3, 1.0.x-dev].
    - phpunit/phpunit 7.5.x-dev requires phar-io/manifest ^1.0.2 -> satisfiable by phar-io/manifest[1.0.2, 1.0.3, 1.0.x-dev].
    - Can only install one of: phar-io/manifest[1.0.2, 1.0.1].
    - Can only install one of: phar-io/manifest[1.0.3, 1.0.1].
    - Can only install one of: phar-io/manifest[1.0.x-dev, 1.0.1].
    - Installation request for phar-io/manifest (locked at 1.0.1) -> satisfiable by phar-io/manifest[1.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by OndraM** [comment]
This will be solved with release of version 3.0.
