### ISSUE TITLE
ci-detector shouldn't be required

### ISSUE THREAD

**Issue by oliver-zhou** [lmc-eu/steward#240]
ondram/ci-detector shouldn't be in the composer.json requirements, and should only be in the dev dependencies, and people should pull the ci-detector in manually when CI is desired.

By having it there, when people use lmc/steward in an environment building on CircleCI, it kicks off unexpected CircleCI builds. 

ci-detector is also running circleci 1.0 builds, which is depreciated.

OndraM/ci-detector#35

**Comment by OndraM** [comment]
CI-detector is used to auto-detect whether Steward is run on CI, this is why it is required.

> By having it there, when people use lmc/steward in an environment building on CircleCI, it kicks off unexpected CircleCI builds.

Sorry, I don't understand, how is this possible? Ci-detector is installed into vendor library, and Circle CI shouldn't care about files installed there (ie. it it should not trigger CI build). Or it does? Do you have some reproducible example?
