### ISSUE TITLE
keep test running even on failed assertion

### ISSUE THREAD

**Issue by tomthedude** [lmc-eu/steward#248]
hello,
i want the test case to keep runing even if there is a failed assertion, i have tried the following solutions

```php
public function testDemo()
{
    $failures = [];
    try {
        $this->assertTrue(false);
    } catch(PHPUnit_Framework_ExpectationFailedException $e) {
        $failures[] = $e->getMessage();
    }
    try {
        $this->assertTrue(false);
    } catch(PHPUnit_Framework_ExpectationFailedException $e) {
        $failures[] = $e->getMessage();
    }
    if(!empty($failures))
    {
        throw new PHPUnit_Framework_ExpectationFailedException (
            count($failures)." assertions failed:\n\t".implode("\n\t", $failures)
        );
    }
}
```

also tried with  catch(Exception $e)
but it did not work, i guess that some kind of other exception happens?
what can i do?

**Comment by OndraM** [comment]
See https://github.com/sebastianbergmann/phpunit/issues/1322 . It should be theoretically possible using try-catch-finally, you are probably just catching wrong exception.
