### ISSUE TITLE
A question regarding the test file path configuration...

### ISSUE THREAD

**Issue by KLA6** [lmc-eu/steward#254]
I'm sorry that this question is because of my short knowledge about the environments.

What if I want to locate all my test files in a different named folder (not "tests", but e.g. "test_selenium"), how can I do it...?

Basically the test file path is fixed by the other libraries which Steward are using, so it can not be change-able...?

Thank you for reading my questions.

**Comment by OndraM** [comment]
Hi, you can use either command line option when starting steward command:
```
bin/steward run --tests-dir=tests_selenium/ [environment] [browser]
```

or you can store default in [`steward.yml` configuration file](https://github.com/lmc-eu/steward/wiki/Configuration-file).
