### ISSUE TITLE
Screen sizes configuration doesn't work

### ISSUE THREAD

**Issue by andreaschiffo** [lmc-eu/steward#291]
I'm putting together a suite using steward, want to have different configs for different screen sizes so I'm testing different settings in the custom `AbstractTestCase` (see [steward-example](https://github.com/lmc-eu/steward-example) from which I've copied over this class) but no change seems to apply to the window size. Pseudo-random sizes (unrelated to any other default config) seem to be applying instead.

Any hints please?

Attaching debug screenshots:

Size resulting after having applied default settings in `\Lmc\Steward\Test\AbstractTestCase`:

![image](https://user-images.githubusercontent.com/10629167/141558120-9e6b726e-21d0-4d8f-9687-156a5e396381.png)

Size **before** setting custom size in local `ACME\QAAutomation\AbstractTestCase`:

![image](https://user-images.githubusercontent.com/10629167/141559509-4c0591dd-bb42-4635-ba97-3d769487f91b.png)

Size **after** having set custom size in local `ACME\QAAutomation\AbstractTestCase:`

![image](https://user-images.githubusercontent.com/10629167/141559943-27bc5a6c-79c9-4109-b351-302eacc4dce1.png)

**Comment by OndraM** [comment]
Hi,
from my experience, setting browser size through webdriver has some limits and is not consistent in different browsers. For example - the default size 1280x1024 is size of the whole window, but when you call getSize, some browsers returns size of the website viewport. So this is a bit smaller - you have eg. address bar on the top, and scrollbar on the size, which are not part of the viewport. But you can just run it yourselves (in not-headless mode) and have a look what size it actually returns. 

As per the small size - some browsers do have "minimal" size, and they will not allow to be set smaller than that. You can try setting the size to eg. 1x1 and you will see what is the minimum window size the browser allows. This is also different for each browser.

However this is defined behavior in the W3C WebDriver specs:
> The specification does not guarantee that the resulting window size will exactly match that which was requested. In particular the implementation is expected to clamp values that are larger than the physical screen dimensions, or smaller than the minimum window size. 

https://w3c.github.io/webdriver/#set-window-rect

**Comment by andreaschiffo** [comment]
Thanks @OndraM 
Is setting the size via browser capabilities more reliable by any chance?
Like, my aim would be to give the chance of running tests on mobile-like screen sizes.

**Comment by OndraM** [comment]
Yes, I think this should not be a problem. But you cannot rely on the exact screen dimension.

For example - if you have threshold for the mobile view like 800 px, you can just set screen width to somehing like 750 and you will be fine. And vice versa - if you have desktop version on threshold 1024, just set the width to eg. 1200 and there should be no issues.

**Comment by andreaschiffo** [comment]
Screen size must be determined as described above. Thanks @OndraM, closing this issue.
