### ISSUE TITLE
Support for php8?

### ISSUE THREAD

**Issue by ipsod** [lmc-eu/steward#292]
`composer require lmc/steward`

```
Using version ^1.1 for lmc/steward
./composer.json has been updated
Running composer update lmc/steward
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - lmc/steward[1.1.0, ..., 1.1.1] require ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
    - lmc/steward[1.2.0, ..., 1.5.1] require php ^5.5.5 || ~7.0 -> your php version (8. 1.0RC6) does not satisfy that requirement.
    - Root composer.json requires lmc/steward ^1.1 -> satisfiable by lmc/steward[1.1.0, ..., 1.5.1].
```

**Comment by OndraM** [comment]
Hi, PHP 8 support is available in main branch (which will soon be released as version 3).

To use it now, run
```sh
composer require lmc/steward:3.0.x-dev
```

**Comment by OndraM** [comment]
(From the error log it also seems you will need to enable ext-zip PHP extension.)

**Comment by ipsod** [comment]
@OndraM 

Still having trouble:

```
  Problem 1
    - lmc/steward 3.0.x-dev is an alias of lmc/steward dev-master and thus requires it to be installed too.
    - lmc/steward 3.0.x-dev is an alias of lmc/steward dev-main and thus requires it to be installed too.
    - lmc/steward dev-master requires php ^7.1 -> your php version (8.1.0RC6) does not satisfy that requirement.
    - lmc/steward dev-main requires phpunit/phpunit ^8.5.15 -> found phpunit/phpunit[8.5.15, ..., 8.5.21] but it conflicts with your root composer.json
    - Root composer.json requires lmc/steward 3.0.x-dev -> satisfiable by lmc/steward[3.0.x-dev (alias of dev-master)].
```

My root composer.json requires `"phpunit/phpunit": "^9"`.  I can change that, if I need to, but was still seeing an error regarding PHP version.

**Comment by OndraM** [comment]
See https://github.com/lmc-eu/steward#1-install-steward

> For most cases we recommend having functional tests in the same repository as your application **but in a separate folder** 
We suggest putting them in a `selenium-tests/` directory.

=> We do not recommend putting end to end tests in the same directory as you application. The best is to have separate composer.json, with dependencies relevant only for your selenium tests, because dependencies of Steward are not relevant for your application, so you should not mix them. I guess this is whats causes this issue.
