### ISSUE TITLE
Example repository with real tests

### ISSUE THREAD

**Issue by OndraM** [lmc-eu/steward#4]
We should prepare example repository with real tests, that will:
- [x] ~~Describe how to begin writing tests using Steward (set-up, composer etc.)~~ Covered in [getting started](https://github.com/lmc-eu/steward#getting-started)
- [x] Show features and extensibility of AbstractTestCase
- [x] Include custom component extending AbstractComponent and using PageObject design pattern
- [ ] ~~Include custom EventListener extending Steward with custom option~~ moved to https://github.com/lmc-eu/steward-example/issues/13
- [x] Be run periodically on Travis CI in Phantomjs
- [x] Be run periodically on Travis CI in Firefox (nice to have)
- [x] Add note about the example project to the main README

**Comment by OndraM** [comment]
Being prepared here: https://github.com/lmc-eu/steward-example

**Comment by OndraM** [comment]
The phantomjs build [works](https://travis-ci.org/lmc-eu/steward-example/builds), but to be run periodically, it needs some external service like http://traviscron.pythonanywhere.com/, because this is not yet implemented in Travis (https://github.com/travis-ci/travis-ci/issues/582)

EDIT: periodic build on Travis is triggered from our Jenkins by API call every 12 hours: https://travis-ci.org/lmc-dummy/steward-example

**Comment by wazelin** [comment]
Hi @OndraM,
I cannot understand how can I add new or extend existing WebDriverListener. Without it I can't see how can I set custom capabilities.
Could you please give me some hint?

**Comment by OndraM** [comment]
@Wazelin Hi, for now I would suggest using 2.0 development branch (`composer require lmc/steward:2.0.x-dev`), where you can simply pass custom capabilities on command line like this:

```
./vendor/bin/steward run production firefox --capability="platform:WIN7"
```

Current option through extending the WebDriverListener class is a bit tricky and I'm currently working on simplifying it (you need not only extend WebDriverListener, but also implement custom listener which will allow you to pass PHPUnit process you custom phpunit.xml...). So i recommend the 2.0 branch :).

**Comment by wazelin** [comment]
@OndraM, are you sure --capability gets parsed OK?
I've tried to use it that way but it includes quotes to the key and the value.
I think it needs `trim($capability, '"\'')` in `encodeCapabilties` method.

**Comment by OndraM** [comment]
@Wazelin Hi, it should work fine. What is the whole command you use?

**Comment by wazelin** [comment]
For example `--capability="deviceName:Galaxy Nexus"` in my case gets parsed into key `"deviceName` with value `Galaxy Nexus"`.

**Comment by OndraM** [comment]
That is weird, this works for me, this is the dump of `$parts` in the `encodeCapabilties()` method

```
array(2) {
  [0]=>
  string(10) "deviceName"
  [1]=>
  string(12) "Galaxy Nexus"
}
```

In what environment do you run it? The argument parsing is done by the Symfony Console component, so it should work fine. There is even [testcase exactly for this in Steward](https://github.com/lmc-eu/steward/blob/2.0/src-tests/Process/ProcessSetCreatorTest.php#L266).

Maybe some escaping by CI server/shell could take a place? Where do you run the command?

**Comment by wazelin** [comment]
That is really weird.
I ran it from PHPStorm's command line tool.

Using proper terminal solved the issue. Thanks =)

**Comment by OndraM** [comment]
Other features not yet shown in example repository moved to separate issues: https://github.com/lmc-eu/steward-example/labels/enhancement
